name: Package and Upload

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run package script
        run: bash package.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beszel_agent-for-magisk
          path: module/
          if-no-files-found: error