name: Package and Upload

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run package script
        run: bash package.sh

      - name: Write version information
        run: |
          module/beszel/bin/x64 version
          git rev-list --count --all
          sed -i "s/AGENT_VERSION/$(module/beszel/bin/x64 version | sed 's/beszel-agent //')/g" module/module.prop
          sed -i "s/VERSION_CODE/$(git rev-list --count --all)/g" module/module.prop
          cat module/module.prop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beszel_agent-for-magisk
          path: module/
          if-no-files-found: error